services:
  - type: web
    name: thejerkhut
    env: static
    buildCommand: ""
    publishDir: "."
    headers:
      - path: "/*"
        name: "Cache-Control"
        value: "public, max-age=0, must-revalidate"
